version: 2
updates:
  - package-ecosystem: npm
    directory: /
    schedule:
      interval: weekly
      day: monday
      time: "03:00"
      timezone: Asia/Shanghai
    groups:
      all-npm:
        patterns:
          - "*"
    open-pull-requests-limit: 1

  - package-ecosystem: github-actions
    directory: /
    schedule:
      interval: weekly
      day: monday
      time: "03:30"
      timezone: Asia/Shanghai
    groups:
      all-github-actions:
        patterns:
          - "*"
    open-pull-requests-limit: 1
